# Generated by Django 4.0.1 on 2023-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_no', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_no', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=200)),
                ('city', models.ManyToManyField(to='myapp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('case_type', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('city', models.ManyToManyField(to='myapp.City')),
            ],
        ),
    ]
