# Generated by Django 4.0.1 on 2023-09-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='city',
            field=models.ManyToManyField(to='myapp.State'),
        ),
    ]
