# Generated by Django 4.0.1 on 2023-09-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_state_city_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='state',
            field=models.ManyToManyField(to='myapp.State'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='city',
            field=models.ManyToManyField(to='myapp.City'),
        ),
    ]
